version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"